// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/hueter57/catalyst/backend/internal/ent/assignee"
	"github.com/hueter57/catalyst/backend/internal/ent/task"
)

// Assignee is the model entity for the Assignee schema.
type Assignee struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AssigneeQuery when eager-loading is set.
	Edges         AssigneeEdges `json:"edges"`
	task_assignee *uuid.UUID
	selectValues  sql.SelectValues
}

// AssigneeEdges holds the relations/edges for other nodes in the graph.
type AssigneeEdges struct {
	// Task holds the value of the task edge.
	Task *Task `json:"task,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TaskOrErr returns the Task value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AssigneeEdges) TaskOrErr() (*Task, error) {
	if e.Task != nil {
		return e.Task, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "task"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Assignee) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case assignee.FieldID, assignee.FieldUserID:
			values[i] = new(uuid.UUID)
		case assignee.ForeignKeys[0]: // task_assignee
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Assignee fields.
func (_m *Assignee) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case assignee.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case assignee.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case assignee.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field task_assignee", values[i])
			} else if value.Valid {
				_m.task_assignee = new(uuid.UUID)
				*_m.task_assignee = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Assignee.
// This includes values selected through modifiers, order, etc.
func (_m *Assignee) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTask queries the "task" edge of the Assignee entity.
func (_m *Assignee) QueryTask() *TaskQuery {
	return NewAssigneeClient(_m.config).QueryTask(_m)
}

// Update returns a builder for updating this Assignee.
// Note that you need to call Assignee.Unwrap() before calling this method if this Assignee
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Assignee) Update() *AssigneeUpdateOne {
	return NewAssigneeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Assignee entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Assignee) Unwrap() *Assignee {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Assignee is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Assignee) String() string {
	var builder strings.Builder
	builder.WriteString("Assignee(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteByte(')')
	return builder.String()
}

// Assignees is a parsable slice of Assignee.
type Assignees []*Assignee
