// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hueter57/catalyst/backend/internal/ent/assignee"
	"github.com/hueter57/catalyst/backend/internal/ent/predicate"
)

// AssigneeDelete is the builder for deleting a Assignee entity.
type AssigneeDelete struct {
	config
	hooks    []Hook
	mutation *AssigneeMutation
}

// Where appends a list predicates to the AssigneeDelete builder.
func (_d *AssigneeDelete) Where(ps ...predicate.Assignee) *AssigneeDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AssigneeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AssigneeDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AssigneeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(assignee.Table, sqlgraph.NewFieldSpec(assignee.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AssigneeDeleteOne is the builder for deleting a single Assignee entity.
type AssigneeDeleteOne struct {
	_d *AssigneeDelete
}

// Where appends a list predicates to the AssigneeDelete builder.
func (_d *AssigneeDeleteOne) Where(ps ...predicate.Assignee) *AssigneeDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AssigneeDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{assignee.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AssigneeDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
