// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/hueter57/catalyst/backend/internal/ent/assignee"
	"github.com/hueter57/catalyst/backend/internal/ent/predicate"
	"github.com/hueter57/catalyst/backend/internal/ent/task"
)

// AssigneeUpdate is the builder for updating Assignee entities.
type AssigneeUpdate struct {
	config
	hooks    []Hook
	mutation *AssigneeMutation
}

// Where appends a list predicates to the AssigneeUpdate builder.
func (_u *AssigneeUpdate) Where(ps ...predicate.Assignee) *AssigneeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AssigneeUpdate) SetUserID(v uuid.UUID) *AssigneeUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AssigneeUpdate) SetNillableUserID(v *uuid.UUID) *AssigneeUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTaskID sets the "task" edge to the Task entity by ID.
func (_u *AssigneeUpdate) SetTaskID(id uuid.UUID) *AssigneeUpdate {
	_u.mutation.SetTaskID(id)
	return _u
}

// SetNillableTaskID sets the "task" edge to the Task entity by ID if the given value is not nil.
func (_u *AssigneeUpdate) SetNillableTaskID(id *uuid.UUID) *AssigneeUpdate {
	if id != nil {
		_u = _u.SetTaskID(*id)
	}
	return _u
}

// SetTask sets the "task" edge to the Task entity.
func (_u *AssigneeUpdate) SetTask(v *Task) *AssigneeUpdate {
	return _u.SetTaskID(v.ID)
}

// Mutation returns the AssigneeMutation object of the builder.
func (_u *AssigneeUpdate) Mutation() *AssigneeMutation {
	return _u.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (_u *AssigneeUpdate) ClearTask() *AssigneeUpdate {
	_u.mutation.ClearTask()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AssigneeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AssigneeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AssigneeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AssigneeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AssigneeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(assignee.Table, assignee.Columns, sqlgraph.NewFieldSpec(assignee.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(assignee.FieldUserID, field.TypeUUID, value)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   assignee.TaskTable,
			Columns: []string{assignee.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   assignee.TaskTable,
			Columns: []string{assignee.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{assignee.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AssigneeUpdateOne is the builder for updating a single Assignee entity.
type AssigneeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AssigneeMutation
}

// SetUserID sets the "user_id" field.
func (_u *AssigneeUpdateOne) SetUserID(v uuid.UUID) *AssigneeUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AssigneeUpdateOne) SetNillableUserID(v *uuid.UUID) *AssigneeUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTaskID sets the "task" edge to the Task entity by ID.
func (_u *AssigneeUpdateOne) SetTaskID(id uuid.UUID) *AssigneeUpdateOne {
	_u.mutation.SetTaskID(id)
	return _u
}

// SetNillableTaskID sets the "task" edge to the Task entity by ID if the given value is not nil.
func (_u *AssigneeUpdateOne) SetNillableTaskID(id *uuid.UUID) *AssigneeUpdateOne {
	if id != nil {
		_u = _u.SetTaskID(*id)
	}
	return _u
}

// SetTask sets the "task" edge to the Task entity.
func (_u *AssigneeUpdateOne) SetTask(v *Task) *AssigneeUpdateOne {
	return _u.SetTaskID(v.ID)
}

// Mutation returns the AssigneeMutation object of the builder.
func (_u *AssigneeUpdateOne) Mutation() *AssigneeMutation {
	return _u.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (_u *AssigneeUpdateOne) ClearTask() *AssigneeUpdateOne {
	_u.mutation.ClearTask()
	return _u
}

// Where appends a list predicates to the AssigneeUpdate builder.
func (_u *AssigneeUpdateOne) Where(ps ...predicate.Assignee) *AssigneeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AssigneeUpdateOne) Select(field string, fields ...string) *AssigneeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Assignee entity.
func (_u *AssigneeUpdateOne) Save(ctx context.Context) (*Assignee, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AssigneeUpdateOne) SaveX(ctx context.Context) *Assignee {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AssigneeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AssigneeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AssigneeUpdateOne) sqlSave(ctx context.Context) (_node *Assignee, err error) {
	_spec := sqlgraph.NewUpdateSpec(assignee.Table, assignee.Columns, sqlgraph.NewFieldSpec(assignee.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Assignee.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, assignee.FieldID)
		for _, f := range fields {
			if !assignee.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != assignee.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(assignee.FieldUserID, field.TypeUUID, value)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   assignee.TaskTable,
			Columns: []string{assignee.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   assignee.TaskTable,
			Columns: []string{assignee.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Assignee{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{assignee.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
