// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/hueter57/catalyst/backend/internal/ent/assignee"
	"github.com/hueter57/catalyst/backend/internal/ent/task"
)

// AssigneeCreate is the builder for creating a Assignee entity.
type AssigneeCreate struct {
	config
	mutation *AssigneeMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *AssigneeCreate) SetUserID(v uuid.UUID) *AssigneeCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *AssigneeCreate) SetID(v uuid.UUID) *AssigneeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AssigneeCreate) SetNillableID(v *uuid.UUID) *AssigneeCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetTaskID sets the "task" edge to the Task entity by ID.
func (_c *AssigneeCreate) SetTaskID(id uuid.UUID) *AssigneeCreate {
	_c.mutation.SetTaskID(id)
	return _c
}

// SetNillableTaskID sets the "task" edge to the Task entity by ID if the given value is not nil.
func (_c *AssigneeCreate) SetNillableTaskID(id *uuid.UUID) *AssigneeCreate {
	if id != nil {
		_c = _c.SetTaskID(*id)
	}
	return _c
}

// SetTask sets the "task" edge to the Task entity.
func (_c *AssigneeCreate) SetTask(v *Task) *AssigneeCreate {
	return _c.SetTaskID(v.ID)
}

// Mutation returns the AssigneeMutation object of the builder.
func (_c *AssigneeCreate) Mutation() *AssigneeMutation {
	return _c.mutation
}

// Save creates the Assignee in the database.
func (_c *AssigneeCreate) Save(ctx context.Context) (*Assignee, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AssigneeCreate) SaveX(ctx context.Context) *Assignee {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AssigneeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AssigneeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AssigneeCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := assignee.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AssigneeCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Assignee.user_id"`)}
	}
	return nil
}

func (_c *AssigneeCreate) sqlSave(ctx context.Context) (*Assignee, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AssigneeCreate) createSpec() (*Assignee, *sqlgraph.CreateSpec) {
	var (
		_node = &Assignee{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(assignee.Table, sqlgraph.NewFieldSpec(assignee.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(assignee.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if nodes := _c.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   assignee.TaskTable,
			Columns: []string{assignee.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.task_assignee = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AssigneeCreateBulk is the builder for creating many Assignee entities in bulk.
type AssigneeCreateBulk struct {
	config
	err      error
	builders []*AssigneeCreate
}

// Save creates the Assignee entities in the database.
func (_c *AssigneeCreateBulk) Save(ctx context.Context) ([]*Assignee, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Assignee, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AssigneeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AssigneeCreateBulk) SaveX(ctx context.Context) []*Assignee {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AssigneeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AssigneeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
