// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/hueter57/catalyst/backend/internal/ent/reminder"
	"github.com/hueter57/catalyst/backend/internal/ent/task"
)

// Reminder is the model entity for the Reminder schema.
type Reminder struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// RemindAt holds the value of the "remind_at" field.
	RemindAt time.Time `json:"remind_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ReminderQuery when eager-loading is set.
	Edges         ReminderEdges `json:"edges"`
	task_reminder *uuid.UUID
	selectValues  sql.SelectValues
}

// ReminderEdges holds the relations/edges for other nodes in the graph.
type ReminderEdges struct {
	// Task holds the value of the task edge.
	Task *Task `json:"task,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TaskOrErr returns the Task value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReminderEdges) TaskOrErr() (*Task, error) {
	if e.Task != nil {
		return e.Task, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "task"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Reminder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case reminder.FieldRemindAt:
			values[i] = new(sql.NullTime)
		case reminder.FieldID:
			values[i] = new(uuid.UUID)
		case reminder.ForeignKeys[0]: // task_reminder
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Reminder fields.
func (_m *Reminder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case reminder.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case reminder.FieldRemindAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field remind_at", values[i])
			} else if value.Valid {
				_m.RemindAt = value.Time
			}
		case reminder.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field task_reminder", values[i])
			} else if value.Valid {
				_m.task_reminder = new(uuid.UUID)
				*_m.task_reminder = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Reminder.
// This includes values selected through modifiers, order, etc.
func (_m *Reminder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTask queries the "task" edge of the Reminder entity.
func (_m *Reminder) QueryTask() *TaskQuery {
	return NewReminderClient(_m.config).QueryTask(_m)
}

// Update returns a builder for updating this Reminder.
// Note that you need to call Reminder.Unwrap() before calling this method if this Reminder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Reminder) Update() *ReminderUpdateOne {
	return NewReminderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Reminder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Reminder) Unwrap() *Reminder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Reminder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Reminder) String() string {
	var builder strings.Builder
	builder.WriteString("Reminder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("remind_at=")
	builder.WriteString(_m.RemindAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Reminders is a parsable slice of Reminder.
type Reminders []*Reminder
