// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Assignee is the predicate function for assignee builders.
type Assignee func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Reminder is the predicate function for reminder builders.
type Reminder func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)
